// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function loadConfig() {
    return invoke<ConfigResult>("load_config")
}

export function saveConfig(config: AppConfig) {
    return invoke<ConfigResult>("save_config", { config })
}

export function resetConfig() {
    return invoke<ConfigResult>("reset_config")
}

export function getAudioFiles(audioFileType: AudioFileTypes) {
    return invoke<string[]>("get_audio_files", { audioFileType })
}

export function getAppInfo() {
    return invoke<AppInfo>("get_app_info")
}

export function downloadAudioYt(url: string, videoType: VideoLinkType) {
    return invoke<null>("download_audio_yt", { url,videoType })
}

export type AudioFileTypes = "MP3" | "WAV" | "WEBM"
/**
 * The configuration file for the application
 */
export type AppConfig = { local_audio_folders: string[]; file_filter_types: AudioFileTypes[]; download_folder: string | null; user: AppUser | null }
export type VideoLinkType = "Playlist" | "Video"
export type ConfigResult = { data: AppConfig; error: AppError | null }
/**
 * The User data information saved from discord oauth
 */
export type AppUser = { discord_id: string; access_token: string; refresh_token: string; display_name: string | null }
/**
 * basic Errors returned by the application to the front end.
 */
export type AppError = { status: boolean; message: string }
export type AppInfo = { os: string; name: string; version: string; description: string }
